version: 2
plan:
  project-key: TEST
  key: TEST1
  name: Bamboo-Java-Vulnado Build
stages:
  - Build:
      jobs:
        - BuildJob
  - Test:
      jobs:
        - TestJob
jobs:
  - BuildJob:
      tasks:
        - checkout:
            description: Checkout Code
        - script:
            description: Build Project
            script: |
              mvn clean install
        - artifact:
            name: JAR Files
            paths:
              - target/*.jar
  - TestJob:
      tasks:
        - script:
            description: Run Tests
            script: |
              mvn test
        - artifact:
            name: Test Reports
            paths:
              - target/surefire-reports/*.xml
